In [2]:
import pandas as pd
df = pd.read_csv('starts_data.csv', skiprows=2)
df

c:\Users\Gabriel LÃ³pez\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Sol,0.000000,0.000000.1,0.0000,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,1,0.5,Unnamed: 32,1.1,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,1,1.0,224700.0,NaN,NaN,NaN,NaN,0.000060,1.089009,219.7802,...,NaN,NaN,Psc,1.0,1.0,NaN,9.638290,NaN,NaN,NaN
1,2,2.0,224690.0,NaN,NaN,NaN,NaN,0.000283,-19.498840,47.9616,...,NaN,NaN,Cet,1.0,2.0,NaN,0.392283,NaN,NaN,NaN
2,3,3.0,224699.0,NaN,NaN,NaN,NaN,0.000335,38.859279,442.4779,...,NaN,NaN,And,1.0,3.0,NaN,386.901132,NaN,NaN,NaN
3,4,4.0,224707.0,NaN,NaN,NaN,NaN,0.000569,-51.893546,134.2282,...,NaN,NaN,Phe,1.0,4.0,NaN,9.366989,NaN,NaN,NaN
4,5,5.0,224705.0,NaN,NaN,NaN,NaN,0.000665,-40.591202,257.7320,...,NaN,NaN,Phe,1.0,5.0,NaN,21.998851,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119609,119612\t\t\t\tNN 4385\t\t\t23.996567\t47.76209...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119610,119613\t\t\t\tNN 4386\t\t\t23.996218\t-44.0679...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119611,119614\t\t\t\tNN 4387\t\t\t23.997386\t-34.1119...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119612,119615\t\t\t\tGl 915\t\t\t0.036059\t-43.165974...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119613,Delete me! o_________________o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
import csv
i = 0
with open('starts_data.csv', 'r') as bad_data, open('clean_data.csv', 'w', newline = '') as good_data:
    reader = csv.reader(bad_data)
    writer = csv.writer(good_data, delimiter = '|', quoting = csv.QUOTE_ALL)
    # Saltandonos la primera linea 
    next(reader)
    column_names = next(reader)
    column_names = column_names[0].split('~')
    writer.writerow(column_names)
    
    for row in reader:
        # Validando el nÃºmero de columnas
        # if len(row) != 37:
        #     print(row)

        # Cambiando tabuladores por comas
        if '\t' in row[0]:
            row_string = row[0]
            row_string = row_string.replace('\t', ',')
            row_string = row_string.split(',')
            writer.writerow(row_string)            

        if row[0] == 'Delete me! o_________________o':
            break

        writer.writerow(row)

        # if i >= 119607:
        #     print(row)
        # i += 1